#!/usr/bin/env bash

# TFHOME can be like, for example, /usr/local/bin
TF=${TFHOME}/terraform

#######################
# 
# Check for Terraform
# executable in the
# set env variable,
# 'TFHOME'
#
#######################
if [ ! -x "${TF}" ]; then
  if [ "${TFHOME}" ]; then
    echo "terraform not found. TFHOME is ${TFHOME}"
    exit 1
  else
    echo "TFHOME is not set."
    exit 1
  fi
fi


TFVARS=""
TFVARS+="--var-file terraform.tfvars"

BECONFIGS=""
BECONFIGS+="--backend-config=tf_state.conf"


#######################
# 
# Build the stack in 
# this order.
#######################
modules=(
  vpc
  iam
  harbor
  jenkins
)

do_init() {
  echo ""
  ${TF} init ${BECONFIGS} "$@" 2>&1
  if [[ $? != 0 ]]; then do_error $? "init ${PWD##*/}"; fi
}

do_apply() {
  echo ""
  ${TF} apply --input=false ${TFVARS} ${BECONFIGS} "$@" 2>&1
  if [[ $? != 0 ]]; then do_error $? "apply ${PWD##*/}"; fi
}

do_build() {
  do_init
  do_apply 
  return $?
}

#######################
# 
# Start with network 
# as foundation, and
# the tools used by
# CI before setting up
# CI infra. 
#######################
do_build_stack() {
  for i in "${modules[@]}"
  do
    echo "do_build_stack(): Building stack ${i}..."
    cd "${i}" && 
    do_build "${i}" &&
    cd ..
    err=$?
    if [[ ${err} -ne 0 ]]; then do_error "Error building stack ${i}"; fi
  done
  return ${err}
}

#######################
# 
# Purge the temporary
# files generated by
# terraform.
#######################
do_clean_stack() {
  echo ""
  return $?
}

#######################
# 
# Tear down the stack.
#######################
do_destroy_stack() {
  echo ""
  return $?
}

do_error() {
  echo ""
  return $?
}

do_help() {
  echo -e "\nUsage: $0 [stack-subcommand]"
  echo -e "\nExamples: "
  echo -e "\n$0 build_stack"
  echo -e "\n$0 clean_stack"
  echo -e "\n$0 destroy_stack"
  echo ""
}

do_show() {
  echo -e "\nOutput the key info used to standup the tech stack"
}

homedir=$(pwd)
SUBCOMMAND=$1
shift

if [[ -z ${SUBCOMMAND} ]]; then
  echo "Error: Need to specify SUBCOMMAND"
  echo ""
  do_help
  exit 1
fi

#######################
# 
# 
#######################
case ${SUBCOMMAND} in
    "" | "-h" | "--help")
        do_help
        ;;
    "show")
         do_show
         exit 0
         ;;
    *_stack)
         #config_access
         "do_${SUBCOMMAND}" "$@" 2>/dev/null
         retv=$?
         cd "${homedir}" || exit 1
         do_error ${retv}
         ;;
esac