---
  - name: Add Docker CE GPG
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker CE repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Docker
    apt:
      state: present
      pkg:
        - "docker-ce"
        - "docker-ce-cli"
        - "containerd.io"

  - name: Enable and start Docker service
    service:
      name: docker
      state: started
      enabled: yes
  
  - name: Permit 'ubuntu' user to access Docker socket
    user:
      name: ubuntu
      groups: docker
      append: yes